Prepare for SQLAlchemy 2
chopshop-166/SignInWebApp pull request #32
Opened 2022-09-17 22:19 UTC by msoucy

Part 1

2022-09-17 22:54 UTC, bot190 requested changes

2022-09-17 22:54 UTC, bot190 commented on signinapp/event.py
> +    ev: Event = db.session.execute(
Any reason not to use `scalar` instead of `execute` here, and elsewhere?

2022-09-17 22:54 UTC, bot190 commented on signinapp/model.py
> +def get_form_ids(model, prefix=False):
`prefix` does not do at all what I was expecting.. Maybe `add_none_option` or something?

2022-09-17 22:54 UTC, bot190 commented on signinapp/model.py
> +        return cls.query.filter_by(name=name).one_or_none()
```suggestion
        return db.session.scalar(select(cls).filter_by(name=name))
```

2022-09-17 22:54 UTC, bot190 commented on signinapp/templates/profile.html.jinja2
> +                       href="{{ url_for('user.badge', badge_id=b)}}">{{ show_badge(b)}}</a>
Does this give the correct URL still?

2022-09-17 23:03 UTC, msoucy commented on signinapp/templates/profile.html.jinja2
> +                       href="{{ url_for('user.badge', badge_id=b)}}">{{ show_badge(b)}}</a>
..... no.

2022-09-17 23:04 UTC, msoucy commented on signinapp/templates/profile.html.jinja2
> +                       href="{{ url_for('user.badge', badge_id=b)}}">{{ show_badge(b)}}</a>
Yes

2022-09-18 03:28 UTC, bot190 approved these changes

2022-09-18 03:32 UTC, merged